import { cadastrarUsuario, loginUsuario, logoutUsuario, observarSessao } from './auth.js';

// Executa assim que o documento HTML estiver pronto
window.addEventListener('DOMContentLoaded', () => {
    
        // Mapeamento dos elementos do HTML
            const areaAuth = document.getElementById('areaAuth');
                const areaCarteira = document.getElementById('areaCarteira');
                    const areaAnalise = document.getElementById('areaAnalise');
                        
                            const btnEntrar = document.getElementById('btnEntrar');
                                const btnCadastrar = document.getElementById('btnCadastrar');
                                    const btnSair = document.getElementById('btnSair');
                                        
                                            const emailInput = document.getElementById('email');
                                                const senhaInput = document.getElementById('senha');

                                                    /**
                                                         * Controla o que aparece na tela dependendo se o usuário está logado ou não
                                                              */
                                                                  function gerenciarInterface(session) {
                                                                          if (session && session.user) {
                                                                                      // Usuário Logado: Esconde login, mostra painel e carteira
                                                                                                  if (areaAuth) areaAuth.style.display = 'none';
                                                                                                              if (areaCarteira) areaCarteira.style.display = 'block';
                                                                                                                          if (areaAnalise) areaAnalise.style.display = 'block';
                                                                                                                                      if (btnSair) btnSair.style.display = 'inline-block';
                                                                                                                                                  console.log("Usuário autenticado:", session.user.email);
                                                                                                                                                          } else {
                                                                                                                                                                      // Usuário Deslogado: Mostra login, esconde painel e carteira
                                                                                                                                                                                  if (areaAuth) areaAuth.style.display = 'block';
                                                                                                                                                                                              if (areaCarteira) areaCarteira.style.display = 'none';
                                                                                                                                                                                                          if (areaAnalise) areaAnalise.style.display = 'none';
                                                                                                                                                                                                                      if (btnSair) btnSair.style.display = 'none';
                                                                                                                                                                                                                                  console.log("Nenhum usuário logado.");
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                  // 1. Monitorar o estado da sessão (Persistência)
                                                                                                                                                                                                                                                      observarSessao((session) => {
                                                                                                                                                                                                                                                              gerenciarInterface(session);
                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                      // 2. Evento de Cadastro
                                                                                                                                                                                                                                                                          if (btnCadastrar) {
                                                                                                                                                                                                                                                                                  btnCadastrar.addEventListener('click', async (e) => {
                                                                                                                                                                                                                                                                                              e.preventDefault();
                                                                                                                                                                                                                                                                                                          const email = emailInput?.value.trim();
                                                                                                                                                                                                                                                                                                                      const senha = senhaInput?.value.trim();

                                                                                                                                                                                                                                                                                                                                  if (!email || !senha) {
                                                                                                                                                                                                                                                                                                                                                  alert("Por favor, preencha todos os campos.");
                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                          await cadastrarUsuario(email, senha);
                                                                                                                                                                                                                                                                                                                                                                                                                          alert("Cadastro realizado! Verifique seu e-mail se necessário.");
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      alert("Erro no cadastro: " + error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 3. Evento de Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (btnEntrar) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              btnEntrar.addEventListener('click', async (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const email = emailInput?.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const senha = senhaInput?.value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!email || !senha) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert("Por favor, preencha todos os campos.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await loginUsuario(email, senha);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alert("Login efetuado com sucesso!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert("Erro no login: " + error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 4. Evento de Logout (Sair)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (btnSair) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          btnSair.addEventListener('click', async (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await logoutUsuario();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert("Você saiu da conta.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert("Erro ao sair: " + error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      