// 1. Obter a instância global com segurança
const supabase = window.supabaseCliente;


// Elementos do DOM
const areaAuth = document.getElementById('areaAuth');
const areaCarteira = document.getElementById('areaCarteira');
const areaAnalise = document.getElementById('areaAnalise'); // Secção do Analisador
const btnEntrar = document.getElementById('btnEntrar');
const btnCadastrar = document.getElementById('btnCadastrar');
const btnSair = document.getElementById('btnSair');
const emailInput = document.getElementById('email');
const senhaInput = document.getElementById('senha');
const msgAuth = document.getElementById('msgAuth');

const buscaAtivo = document.getElementById('buscaAtivo');
const btnAnalisar = document.getElementById('btnAnalisar');
const resultadoAnalise = document.getElementById('resultadoAnalise');
const scoreDestaque = document.getElementById('score');

// Função auxiliar para exibir mensagens de feedback
function exibirMensagem(texto, tipo) {
    msgAuth.textContent = texto;
        msgAuth.className = `feedback-msg ${tipo}`;
        }

        // Funções para alternar as telas
        function mostrarPainelPrivado(user) {
            areaAuth.style.display = 'none';
                areaCarteira.style.display = 'block';
                    areaAnalise.style.display = 'block'; // Mostra o analisador APENAS após o login!
                        btnSair.style.display = 'inline-block';
                            limparFormularios();
                                if (typeof atualizarCarteiraInterface === 'function') {
                                        atualizarCarteiraInterface(user.id);
                                            }
                                            }

                                            function mostrarAreaLogin() {
                                                areaAuth.style.display = 'block';
                                                    areaCarteira.style.display = 'none';
                                                        areaAnalise.style.display = 'none'; // Esconde o analisador na tela de login!
                                                            btnSair.style.display = 'none';
                                                                limparFormularios();
                                                                }

                                                                function limparFormularios() {
                                                                    emailInput.value = '';
                                                                        senhaInput.value = '';
                                                                            msgAuth.textContent = '';
                                                                                msgAuth.className = 'feedback-msg';
                                                                                }

                                                                                // Verificação do Estado da Sessão ao carregar a página
                                                                                document.addEventListener('DOMContentLoaded', async () => {
                                                                                    try {
                                                                                            if (!supabase || typeof supabase.auth === 'undefined') {
                                                                                                        exibirMensagem("Erro: O cliente do Supabase não foi inicializado corretamente.", "erro");
                                                                                                                    return;
                                                                                                                            }

                                                                                                                                    const { data: { session }, error } = await supabase.auth.getSession();
                                                                                                                                            if (session) {
                                                                                                                                                        mostrarPainelPrivado(session.user);
                                                                                                                                                                } else {
                                                                                                                                                                            mostrarAreaLogin();
                                                                                                                                                                                    }
                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                console.error("Erro ao iniciar sessão:", err);
                                                                                                                                                                                                        exibirMensagem(`Erro de inicialização: ${err.message}`, "erro");
                                                                                                                                                                                                            }
                                                                                                                                                                                                            });

                                                                                                                                                                                                            // Fluxo de Cadastro
                                                                                                                                                                                                            btnCadastrar.addEventListener('click', async () => {
                                                                                                                                                                                                                const email = emailInput.value.trim();
                                                                                                                                                                                                                    const password = senhaInput.value.trim();

                                                                                                                                                                                                                        if (!email || !password) {
                                                                                                                                                                                                                                exibirMensagem("Preencha todos os campos para cadastrar.", "erro");
                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                exibirMensagem("A cadastrar...", "info");

                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                            const { data, error } = await supabase.auth.signUp({
                                                                                                                                                                                                                                                                        email,
                                                                                                                                                                                                                                                                                    password,
                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                exibirMensagem(`Erro no cadastro: ${error.message}`, "erro");
                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                    exibirMensagem("Conta criada com sucesso! Faça login para entrar.", "sucesso");
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                        console.error(err);
                                                                                                                                                                                                                                                                                                                                                                exibirMensagem(`Erro de conexão: ${err.message}`, "erro");
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                    // Fluxo de Login
                                                                                                                                                                                                                                                                                                                                                                    btnEntrar.addEventListener('click', async () => {
                                                                                                                                                                                                                                                                                                                                                                        const email = emailInput.value.trim();
                                                                                                                                                                                                                                                                                                                                                                            const password = senhaInput.value.trim();

                                                                                                                                                                                                                                                                                                                                                                                if (!email || !password) {
                                                                                                                                                                                                                                                                                                                                                                                        exibirMensagem("Preencha todos os campos para entrar.", "erro");
                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                        exibirMensagem("A autenticar...", "info");

                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                    const { data, error } = await supabase.auth.signInWithPassword({
                                                                                                                                                                                                                                                                                                                                                                                                                                email,
                                                                                                                                                                                                                                                                                                                                                                                                                                            password,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exibirMensagem(`Erro: ${error.message}`, "erro");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarPainelPrivado(data.user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exibirMensagem(`Erro de login: ${err.message}`, "erro");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Botão Sair
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btnSair.addEventListener('click', async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await supabase.auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarAreaLogin();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                